### ISSUE TITLE
Can not process Dependency-Check report

### ISSUE THREAD

**Issue by zakabluk** [SonarSecurityCommunity/dependency-check-sonar-plugin#152]
**Describe the bug**
Launched sonar-scanner after  dependency-check.sh and got error:
`java.lang.RuntimeException: Can not process Dependency-Check report.`

**To Reproduce**
ISteps to reproduce the behavior:
1. Install 'SonarQueb 7.7,Dependency-Check 1.1.1, SonarJS 5.1.1 (build 7506) '
2. Run 'npm install && dependency-check.sh --format ALL -s . --out reports/ --project "blu"' && sonar-scanner
in sonar-project.properties
```
sonar.dependencyCheck.reportPath=reports/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=reports/dependency-check-report.html
```

**Current behavior**
I received error:
```
15:02:02.091 ERROR: Error during SonarQube Scanner execution
java.lang.RuntimeException: Can not process Dependency-Check report.
	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:233)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
```

**Versions (please complete the following information):**
 - dependency-check version 5.0.0-M3
 - sonarqube 7.7
 - dependency-check-sonar-plugin 1.1.1

**Comment by zakabluk** [comment]
Was wrong dependency-check-sonar-plugin version.
