### ISSUE TITLE
NullPointerException in org.sonar.dependencycheck.base.DependencyCheckUtils.cvssToSonarQubeSeverity

### ISSUE THREAD

**Issue by dbsanfte** [SonarSecurityCommunity/dependency-check-sonar-plugin#164]
**Describe the bug**
NullPointerException trying to pick up a report I generated with the CLI for a Java project. It barfs parsing the report:

> INFO: Sensor OWASP Dependency-Check [dependencycheck]
> INFO: Process Dependency-Check report
> INFO: Process Dependency-Check report (done) | time=92ms
> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 8.070s
> INFO: Final Memory: 52M/436M
> INFO: ------------------------------------------------------------------------
> ERROR: Error during SonarQube Scanner execution
> java.lang.RuntimeException: Can not process Dependency-Check report.
> 	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:213)
> 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
> 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
> 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
> 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
> 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
> 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
> 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
> 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
> 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
> 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
> 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
> 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
> 	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
> 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
> 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
> 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
> 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
> 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
> Caused by: java.lang.NullPointerException
> 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
> 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 	at java.lang.Double.parseDouble(Double.java:538)
> 	at org.sonar.dependencycheck.base.DependencyCheckUtils.cvssToSonarQubeSeverity(DependencyCheckUtils.java:43)
> 	at org.sonar.dependencycheck.DependencyCheckSensor.addIssue(DependencyCheckSensor.java:76)
> 	at org.sonar.dependencycheck.DependencyCheckSensor.addIssues(DependencyCheckSensor.java:138)
> 	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:209)
> 	... 32 more
> ERROR: 
> ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**To Reproduce**
Would be a bugbear to pull the generated XML out of the container at build time. Given the stack trace I would think it shouldn't be necessary.

**Current behavior**
Boom

**Expected behavior**
No boom

**Versions (please complete the following information):**
 - dependency-check 5.0.2
 - sonarqube 6.7
 - dependency-check-sonar-plugin 

**Additional context**

**Comment by dbsanfte** [comment]
Nevermind, it turns out this was due to an old version of the plugin on the sonarqube server. Upgrading to 1.1.5 resolved it.
